application: pageoverhead
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: webapp/static/css

- url: /js
  static_dir: webapp/static/js

- url: /
  script: webapp/controller/index.py

- url: /([^/]+)/overheads/([^/]+)/notes.*
  script: webapp/controller/notes.py

- url: /([^/]+)/overheads/?([^/]*)
  script: webapp/controller/overhead.py


