application: weboverhead
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: webapp/static/css

- url: /js
  static_dir: webapp/static/js

- url: /.*
  script: webapp/router.py


