application: pageoverhead
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  expiration: "30s"
  static_files: src/webapp/static/html/index.html
  upload: src/webapp/static/html/index.html
  
- url: /overhead.*
  script: src/webapp/controller/overhead.py
